version: '3.8'

services:
    postgres:
        image: postgres:14.9
        container_name: postgres-container
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: august_sender
        ports:
            - "5432:5432"

    react:
        image: react:latest
        build:
            context: ./frontend
        container_name: react-container
        ports:
            - "3000:3000"

    mainapp:
        image: django:4.2.4
        container_name: django-container
        build:
            context: ./
        ports:
            - "8000:8000"
        depends_on:
            - postgres
        environment:
            DEBUG: "True"
            DB_NAME: "august_sender"
            DB_USER: "postgres"
            DB_PASSWORD: "postgres"
            DB_HOST: "postgres-container"
            DB_PORT: 5432
            SECRET_KEY: "secret"