# Generated by Django 4.2.4 on 2023-10-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('contact', models.TextField(blank=True, max_length=200, verbose_name='Контакт')),
                ('where_from', models.TextField(blank=True, max_length=200, verbose_name='Источник заказа')),
                ('oder_details', models.TextField(blank=True, max_length=200, verbose_name='Индивидуальные условия заказа')),
                ('address', models.TextField(blank=True, max_length=200, verbose_name='Адрес доставки')),
                ('notes', models.TextField(blank=True, max_length=200, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
